package com.example.amazonq;

import java.util.ArrayList;
import java.util.List;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

// Code generated by Amazon Q chat (imports only included when asked for)
@RestController
public class FibonacciController {

    @GetMapping("/fibonacci")
    public List<Integer> getFibonacciSequence(@RequestParam(defaultValue = "5") int num) {

        if(num < 1) {
            throw new ResponseStatusException(
                org.springframework.http.HttpStatus.BAD_REQUEST,
                "Number must be positive");
        }

        // Code generated by AWS CodeWhisperer autocomplete
        // Throw bad request if n is greater than 20
        if(num > 20) {
            throw new ResponseStatusException(
                org.springframework.http.HttpStatus.BAD_REQUEST,
                "Number must be less than 20");  // throw bad request if n is greater than 20
        }

        return calculateFibonacci(num);
    }


    private List<Integer> calculateFibonacci(int num) {

        List<Integer> fibonacci = new ArrayList<>();
        fibonacci.add(0);
        fibonacci.add(1);

        for(int i=2; i<num; i++) {
            fibonacci.add(fibonacci.get(i-1) + fibonacci.get(i-2));
        }

        return fibonacci;
    }

}
