package com.example.sourcegraphcody;

import java.util.ArrayList;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

// Code generated by Cody chat with human intervention (added package and imports)
@RestController
public class FibonacciController {

    @GetMapping("/fibonacci")
    public List<Integer> getFibonacciSequence(@RequestParam(defaultValue = "5") int n) {

        if (n <= 0) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Number must be greater than zero");
        }

        // Code generated by Cody autocomplete
        // Throw bad request if n is greater than 20
        if (n > 20) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Number must be less than 20");
        }

        List<Integer> fibonacciSequence = new ArrayList<>();

        for (int i = 0; i < n; i++) {
            fibonacciSequence.add(fibonacci(i));
        }

        return fibonacciSequence;

    }

    private int fibonacci(int n) {
        if (n <= 1) {
            return n;
        }
        return fibonacci(n - 1) + fibonacci(n - 2);
    }

}
